### ISSUE TITLE
Delete merged branches

### ISSUE THREAD

**Issue by sebglane** [LKM-code-base/RotatingMHD#174]
There are a lot of stale or merged branches which share very similar names. I intend to delete most of the merged branches to ease the development and to remove old junk.
@j507 What do you think? Do you have any babies left apart from those related to the magnetic induction equation?

**Comment by j507** [comment]
> There are a lot of stale or merged branches which share very similar names. I intend to delete most of the merged branches to ease the development and to remove old junk. @j507 What do you think? Do you have any babies left apart from those related to the magnetic induction equation?

Yeah, a bit of cleaning up would be good. I am not working on any branch apart of on those related to the magnetic induction equation.
